name: Render Reddit Video

on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download Minecraft gameplay
        run: |
          wget -O gameplay.mp4 \
          https://github.com/blatantsurvivor-cpu/reddit-video-renderer/releases/download/v1.0/minecraft_test_1080p.mp4

      - name: Check gameplay
        run: |
          ls -lh gameplay.mp4
          ffprobe -v error \
            -show_entries format=duration,size \
            -of default=noprint_wrappers=1 \
            gameplay.mp4

      - name: Test renderer
        run: |
          echo "GAMEPLAY DOWNLOADED SUCCESSFULLY"
